<?php
// Automatically Generated by TestLink Installer - Mon, 03 Mar 25 14:11:19 +0100
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink_user');
define('DB_PASS', 'testlink_boss');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink_db');
define('DB_TABLE_PREFIX', '');
