<?php
// Automatically Generated by TestLink Installer - Mon, 03 Mar 25 14:11:19 +0100
define('DB_TYPE', 'mysql');
define('DB_USER', 'tl_uat');
define('DB_PASS', 'tl_uat269');
define('DB_HOST', 'localhost');
define('DB_NAME', 'tl_uat');
define('DB_TABLE_PREFIX', '');


// define('DB_TYPE', 'mysql');
// define('DB_USER', 'testlink_user');
// define('DB_PASS', 'NMBplc#25');
// define('DB_HOST', '10.200.224.21:4050');
// define('DB_NAME', 'testlink_db');
// define('DB_TABLE_PREFIX', '');
// --------------------------------------------------------------------------------
