#!/usr/bin/env python3
"""
Build standalone executable for TestLink Optimized Execution Module
Uses PyInstaller to create a real single-file executable with embedded config
"""

import sys
import os
import subprocess
import textwrap
from pathlib import Path


EMBEDDED_CONFIG = """\
DB_HOST=10.200.224.21
DB_PORT=4053
DB_USER=tl_uat
DB_PASSWORD=tl_uat269
DB_NAME=tl_uat

HOST=0.0.0.0
PORT=8000
DEBUG=false
RELOAD=false
LOG_LEVEL=warning

CORS_ORIGINS=http://localhost:8000,http://127.0.0.1:8000,http://test-management.nmbtz.com:9443,https://test-management.nmbtz.com:9443
CORS_ALLOW_CREDENTIALS=true
CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
CORS_ALLOW_HEADERS=Content-Type,Authorization
"""


def write_entrypoint(entrypoint_path: Path, config: str) -> None:
    """
    Write a self-contained entrypoint script that:
    - Writes the .env file on first run
    - Starts the FastAPI app via uvicorn
    """
    # Escape backslashes/quotes so the config embeds safely as a string literal
    safe_config = config.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')

    script = textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"
        TestLink Optimized Execution Module - Standalone Entrypoint
        Auto-generated by build_executable.py — do not edit manually.
        \"\"\"

        import os
        import sys
        from pathlib import Path

        # ── Embedded configuration ────────────────────────────────────────────
        EMBEDDED_CONFIG = \"\"\"{safe_config}\"\"\"

        def bootstrap_env() -> None:
            \"\"\"Write .env to the working directory if it doesn't exist.\"\"\"
            env_path = Path(".env")
            if not env_path.exists():
                env_path.write_text(EMBEDDED_CONFIG)
                print("✅ .env created from embedded configuration")
            else:
                print("ℹ️  .env already exists — skipping creation")

        def main() -> int:
            bootstrap_env()

            # Load .env into the environment before importing the app
            try:
                from dotenv import load_dotenv
                load_dotenv(override=False)
            except ImportError:
                print("⚠️  python-dotenv not found; relying on system environment")

            host = os.getenv("HOST", "0.0.0.0")
            port = int(os.getenv("PORT", "8000"))

            print("🚀 Starting TestLink Optimized Execution API...")
            print(f"📍 Docs: http://{{host}}:{{port}}/docs")
            print(f"🏥 Health: http://{{host}}:{{port}}/health")

            try:
                import uvicorn
                from main import app  # your FastAPI app lives in main.py
                uvicorn.run(app, host=host, port=port)
            except ImportError as exc:
                print(f"❌ Missing dependency: {{exc}}")
                print("   Run:  pip install -r requirements.txt")
                return 1

            return 0

        if __name__ == "__main__":
            sys.exit(main())
    """)

    entrypoint_path.write_text(script, encoding="utf-8")
    print(f"✅ Entrypoint written → {entrypoint_path}")


def install_pyinstaller() -> None:
    """Ensure PyInstaller is available."""
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("📦 PyInstaller not found — installing...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])


def build_executable(entrypoint: Path, output_name: str = "TestLinkOptimizedExecution") -> None:
    """Run PyInstaller to produce a single-file executable."""
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",                   # single executable
        "--name", output_name,
        "--clean",                     # remove previous build artefacts
        # Add hidden imports that PyInstaller might miss with FastAPI/uvicorn
        "--hidden-import", "uvicorn.logging",
        "--hidden-import", "uvicorn.loops",
        "--hidden-import", "uvicorn.loops.auto",
        "--hidden-import", "uvicorn.protocols",
        "--hidden-import", "uvicorn.protocols.http",
        "--hidden-import", "uvicorn.protocols.http.auto",
        "--hidden-import", "uvicorn.protocols.websockets.auto",
        "--hidden-import", "uvicorn.lifespan.on",
        "--hidden-import", "fastapi",
        "--hidden-import", "mysql.connector",
        str(entrypoint),
    ]

    print(f"🔨 Running PyInstaller: {' '.join(cmd)}")
    result = subprocess.run(cmd)

    if result.returncode != 0:
        print("❌ PyInstaller build failed")
        sys.exit(result.returncode)

    exe_suffix = ".exe" if sys.platform == "win32" else ""
    output_path = Path("dist") / f"{output_name}{exe_suffix}"
    print(f"\n✅ Executable created → {output_path}")
    print(f"📋 Usage: {output_path}")
    print("   The executable writes its .env on first run and starts the API.")


def create_executable() -> None:
    entrypoint = Path("_entrypoint_generated.py")
    try:
        write_entrypoint(entrypoint, EMBEDDED_CONFIG)
        install_pyinstaller()
        build_executable(entrypoint)
    finally:
        # Clean up the temporary entrypoint file
        if entrypoint.exists():
            entrypoint.unlink()


if __name__ == "__main__":
    create_executable()